"""Ajuste tabla de auditoria para campo updated_at, solo se llena si se actualiza el registro

Revision ID: 381735e22185
Revises: b1b804e1f15c
Create Date: 2025-04-14 08:52:29.807400

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '381735e22185'
down_revision: Union[str, None] = 'b1b804e1f15c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
