"""Cambios de nulleable y demas parametros

Revision ID: a6f048ace73a
Revises: f0228948d1a1
Create Date: 2025-04-12 15:53:58.892111

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a6f048ace73a'
down_revision: Union[str, None] = 'f0228948d1a1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('persons', 'second_name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('persons', 'second_last_name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.create_unique_constraint(None, 'persons', ['phone'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'persons', type_='unique')
    op.alter_column('persons', 'second_last_name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('persons', 'second_name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###
