"""Implementación de la base para auditoria

Revision ID: fac6f5d08844
Revises: a6f048ace73a
Create Date: 2025-04-13 22:40:31.997059

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fac6f5d08844'
down_revision: Union[str, None] = 'a6f048ace73a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_persons_email', table_name='persons')
    op.drop_index('ix_persons_id', table_name='persons')
    op.drop_table('persons')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('persons',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('first_name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('second_name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('first_last_name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('second_last_name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('email', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('phone', sa.VARCHAR(length=10), autoincrement=False, nullable=False),
    sa.Column('birth_date', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('avatar', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='persons_pkey'),
    sa.UniqueConstraint('phone', name='persons_phone_key')
    )
    op.create_index('ix_persons_id', 'persons', ['id'], unique=True)
    op.create_index('ix_persons_email', 'persons', ['email'], unique=True)
    # ### end Alembic commands ###
